INSERT INTO momentu.user(email, first_name, last_name, gender, password, username) VALUES ('johnsmith040@gmail.com', 'John', 'Smith', 'Male', '$2a$10$3oaqD7CIe3TQWk4/Mx2yn.ddUBFJ97b1N9gEDP.pFFhwUFjrEgdgq', 'jsmith040');
INSERT INTO momentu.user_role(user_id, role) VALUES (1, 'MEMBER');
INSERT INTO momentu.user(email, first_name, last_name, gender, password, username) VALUES ('jdoe5000@gmail.com', 'Jane', 'Doe', 'Female', '$2a$10$IN6uDvXIhWsz4mjAFknLAuACN4iRxbFtVGFBeOS3OKcVIhXDRZBQy', 'janedoe5');
INSERT INTO momentu.user_role(user_id, role) VALUES (2, 'MEMBER');
INSERT INTO momentu.user_role(user_id, role) VALUES (1, 'ADMIN');
INSERT INTO momentu.user(email, first_name, last_name, gender, password, username) VALUES ('testuser@gmail.com', 'Test', 'User', 'Male', '$2a$10$DigLno.ZIaS6rVcGoZzUtexfo4kEBvyfjlDR6HeS01M1UI2p7WtHq', 'testuser');
INSERT INTO momentu.user_role(user_id, role) VALUES (3, 'MEMBER');
INSERT INTO momentu.user(email, first_name, last_name, gender, password, username) VALUES ('testadminuser@gmail.com', 'Test', 'User', 'Male', '$2a$10$FJvJTJZTqOnEToNeN2inge73g4/65Ub73mkP0CroynsXVVWBXGCvi', 'testadminuser');
INSERT INTO momentu.user_role(user_id, role) VALUES (4, 'MEMBER');
INSERT INTO momentu.user_role(user_id, role) VALUES (4, 'ADMIN');
INSERT INTO momentu.location(city, state) VALUES ('Chicago', 'Illinois');
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#festival', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (2, '#festival', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#festival', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (4, '#festival', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#sports', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (2, '#sports', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#sports', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#art', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#marathon', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#parade', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#shopping', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#show', 1, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#festival', 1, 3);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#sports', 1, 2);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#art', 1, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#marathon', 1, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#parade', 1, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#shopping', 1, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#show', 1, 1);
INSERT INTO momentu.location(city, state) VALUES ('New York', 'New York');
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#art', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (2, '#art', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#art', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#marathon', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#parade', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#shopping', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (2, '#show', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (3, '#show', 2, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#art', 2, 3);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#marathon', 2, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#parade', 2, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#shopping', 2, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#show', 2, 2);
INSERT INTO momentu.location(city, state) VALUES ('Seattle', 'Washington');
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#coffee', 3, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#music', 3, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (2, '#music', 3, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#coffee', 3, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#music', 3, 2);
INSERT INTO momentu.location(city, state) VALUES ('Rockford', 'Illinois');
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#coffee', 4, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#music', 4, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (2, '#music', 4, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#coffee', 4, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#music', 4, 2);
INSERT INTO momentu.location(city, state) VALUES ('Schaumburg', 'Illinois');
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#mall', 5, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (1, '#comedy', 5, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.media_meta(user_id, hashtag_label, location_id, created, removed) VALUES (2, '#comedy', 5, '2017-11-14 21:09:22', FALSE);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#mall', 5, 1);
INSERT INTO momentu.hashtag(label, location_id, count) VALUES ('#comedy', 5, 2);